version: '3.8'

services:
  user-db:
    container_name: user-db
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: user_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    ports:
      - "27017:27017"
    volumes:
      - user_data:/data/db
    networks:
      - finance-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root123
      ME_CONFIG_MONGODB_SERVER: user-db
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "8081:8081"
    depends_on:
      - user-db
    networks:
      - finance-network

networks:
  finance-network:
    driver: bridge

volumes:
  user_data: